### ISSUE TITLE
Mirror http://apt.sw.be not working

### ISSUE THREAD

**Issue by leobewater** [richdynamix/magestead#107]
> $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'package.box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: dev_default_1500565390156_70525
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.1.24) and guest (5.0.10) do not match.
Loaded plugins: priorities
Setting up Install Process
http://apt.sw.be/redhat/el6/en/x86_64/extras/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.0.10
    default: VirtualBox Version: 5.1
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` gcc binutils make perl bzip2

Stdout from the command:

Loaded plugins: priorities
Setting up Install Process

Stderr from the command:

http://apt.sw.be/redhat/el6/en/x86_64/extras/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again

**Comment by hunterleaman** [comment]
Having the same problem. Any luck yet @leocheungswell ?

```
==> local: Fuse seems to not be installed on the virtual machine, installing now
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum -y install fuse

Stdout from the command:

Loaded plugins: priorities
Setting up Install Process


Stderr from the command:

http://apt.sw.be/redhat/el6/en/x86_64/extras/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again
```

**Comment by leobewater** [comment]
@hunterleaman no luck at all. I ended up setting it up in my MAMP Pro and it works.

**Comment by hunterleaman** [comment]
Any ideas @richdynamix ?

**Comment by richdynamix** [comment]
Sorry guys, I haven't seen this issue before. I'll see if I can replicate and get back to you.

**Comment by hunterleaman** [comment]
Error occurs after `magestead vm:up`/`vagrant up` with both existing and newly created projects. 

magestead.yaml:
```
vagrantfile:
    puphpet: false
    advanced: 'false'
    vm:
        box: richdynamix/magestead-centos65-nginx-php56
        box_url: richdynamix/magestead-centos65-nginx-php56
        hostname: magestead-sitename.dev
        memory: '2048'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.47.47
        synced_folder:
            vflsf_uocnhnxzm524:
                sync_type: nfs
magestead:
    apps:
        mba_12345:
            type: magento
            dir: /var/www
            locale: en_US
            default_currency: USD
            db_name: magestead
            base_url: sitename.dev
    os: centos65
    server: nginx
```

Versions:
```
hunterleaman$ vagrant version
Installed Version: 1.9.7
Latest Version: 1.9.7 
You're running an up-to-date version of Vagrant!

hunterleaman$ magestead -V
Magestead CLI 2.2.2

hunterleaman$ php -v
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37)
```
