### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by zamson** [richdynamix/magestead#84]
I'm still trying to figure out best practice of running a Magestead/Vagrant project with same GIT repo on multiple machines.

If I ssh into the box I always end up running into permission errors. Still get permission denied using sudo. The default user is vagrant.

Is there any recipe to fix permission within the magestead/vagrant box. As of now I cannot run `php bin/magento setup:di:compile` because of permission denied for the user vagrant.

Edit: to clarify, only ran `vagrant up`, not `magestead new` since I want to use a existing GIT repo. Magestead sets up the vagrant box  but seems to stop before Magento installation. Is it possible to fix permission after installation?

**Comment by ongerit** [comment]
I modified magestead.yaml below and this helped with the permission issues I was having with the box. I hope this helps. 
```
      synced_folder:
            vflsf_uocnhnxzm524:
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                owner: www-data
                group: www-data
```
